controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

homepage:
    path: /
    controller: App\Controller\HomeController::index

articles:
    path: /articles
    controller: App\Controller\ArticlesController::articles 

admin:
    path: /admin
    controller: App\Controller\AdminController::admin

app_jeux_note:
    path: /jeuxavis/{id}
    controller: App\Controller\JeuxAvisController::app_jeux_note


categories:
    path: /categories
    controller: App\Controller\DefaultController::index

categorie:
    path: /categorie/categories/{id}
    controller: App\Controller\DefaultController::jeuxParCategorie
